/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.elevatorsystem;

import com.elevatorsystem.elevator.Direction;
import com.elevatorsystem.elevator.Elevator;
import com.elevatorsystem.requests.ExternalRequest;
import com.elevatorsystem.requests.InternalRequest;
import com.elevatorsystem.requests.Request;
import org.testng.annotations.*;

public class ElevatorTest {
    /**
     * G-0
     * Max floor - 5
     */

    @Test
    void testElevator1(){
        Elevator elevator = new Elevator();

        //person wants to go in up direction from source floor 2
        ExternalRequest er1 = new ExternalRequest(Direction.UP, 2);

        //the destination floor is 4
        InternalRequest ir1 = new InternalRequest(4);
        Request request1 = new Request(ir1, er1);
        elevator.run(request1);

    }

    @Test
    void testElevator2(){
        Elevator elevator = new Elevator();

        //person wants to go in up direction from source floor 2
        ExternalRequest er1 = new ExternalRequest(Direction.UP, 2);

        //the destination floor is 4
        InternalRequest ir1 = new InternalRequest(4);
        Request request1 = new Request(ir1, er1);
        elevator.run(request1);

        //person wants to go in down direction from source floor 5
        ExternalRequest er2 = new ExternalRequest(Direction.UP, 5);

        //the destination floor is 1
        InternalRequest ir2 = new InternalRequest(1);
        Request request2 = new Request(ir2, er2);
        elevator.run(request2);

        //person wants to go in down direction from source floor 3
        ExternalRequest er3 = new ExternalRequest(Direction.UP, 3);

        //the destination floor is 2
        InternalRequest ir3 = new InternalRequest(2);
        Request request3 = new Request(ir3, er3);
        elevator.run(request3);
    }
}
